In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
# mount drive

## preprocessing

In [ ]:
# data is from 1995 to 2024
data = pd.read_csv("/content/drive/MyDrive/fyp/code/Nifty 50 Historical Data.csv")

In [ ]:
data.head()

         Date     Price      Open      High       Low     Vol. Change %
0  24-11-2015  7,831.60  7,837.00  7,870.35  7,812.65  134.56B   -0.22%
1  23-11-2015  7,849.25  7,869.50  7,877.50  7,825.20  130.87B   -0.09%
2  20-11-2015  7,856.55  7,841.90  7,906.95  7,817.80  156.61B    0.18%
3  19-11-2015  7,842.75  7,788.50  7,854.90  7,765.45  136.70B    1.43%
4  18-11-2015  7,731.80  7,823.15  7,843.40  7,725.05  148.04B   -1.35%

In [ ]:
data.isnull().sum()

Date          0
Price         0
Open          0
High          0
Low           0
Vol.        291
Change %      0
dtype: int64

In [ ]:
data[data.isnull().any(axis=1)]

            Date     Price      Open      High       Low Vol. Change %
2251  21-10-2006  3,683.50  3,680.85  3,708.40  3,662.85  NaN    0.18%
2375  29-04-2006  3,557.60  3,508.35  3,565.75  3,508.35  NaN    1.40%
4710  31-12-1996    899.10    918.15    922.10    895.60  NaN   -1.39%
4711  26-12-1996    911.80    887.95    913.35    887.95  NaN    3.14%
4712  24-12-1996    884.05    881.85    887.50    874.05  NaN    0.23%
...          ...       ...       ...       ...       ...  ...      ...
4994  10-11-1995    948.82    951.93    951.93    946.00  NaN   -0.45%
4995  09-11-1995    953.07    960.32    960.32    952.13  NaN   -1.13%
4996  08-11-1995    964.01    976.28    976.28    962.98  NaN   -1.45%
4997  07-11-1995    978.22    987.17    987.17    977.05  NaN   -1.08%
4998  06-11-1995    988.92  1,001.53  1,001.53    988.92  NaN   -1.11%

[291 rows x 7 columns]

In [ ]:
data.loc[2250:2253]

            Date     Price      Open      High       Low    Vol. Change %
2250  23-10-2006  3,657.30  3,683.40  3,690.85  3,651.20  45.31B   -0.71%
2251  21-10-2006  3,683.50  3,680.85  3,708.40  3,662.85     NaN    0.18%
2252  20-10-2006  3,676.85  3,678.75  3,714.25  3,665.50  71.91B   -0.03%
2253  19-10-2006  3,677.80  3,711.10  3,726.95  3,655.05  87.37B   -0.89%

In [ ]:
data.fillna(0, inplace=True)

In [ ]:
data.dtypes

Date        datetime64[ns]
Price               object
Open                object
High                object
Low                 object
Vol.                object
Change %            object
dtype: object

In [ ]:
data['Date'] = pd.to_datetime(data['Date'], format='%d-%m-%Y')

In [ ]:
# Remove commas and convert to float
for col in ['Price', 'Open', 'High', 'Low']:
    data[col] = data[col].str.replace(',', '').astype(float)

print(data.dtypes)

Date        datetime64[ns]
Price              float64
Open               float64
High               float64
Low                float64
Vol.                object
Change %            object
dtype: object

In [ ]:
# Convert Change % to float
# so now col just contains the percentage as float without % symbol
data['Change %'] = data['Change %'].str.replace('%', '').astype(float)
data.head()

        Date    Price     Open     High      Low     Vol.  Change %
0 2015-11-24  7831.60  7837.00  7870.35  7812.65  134.56B     -0.22
1 2015-11-23  7849.25  7869.50  7877.50  7825.20  130.87B     -0.09
2 2015-11-20  7856.55  7841.90  7906.95  7817.80  156.61B      0.18
3 2015-11-19  7842.75  7788.50  7854.90  7765.45  136.70B      1.43
4 2015-11-18  7731.80  7823.15  7843.40  7725.05  148.04B     -1.35

In [ ]:
# Convert Vol. to float
def convert_vol(value):
    value_str = str(value)  # Convert value to string to handle different types
    if value_str == '0':
        return 0
    if 'B' in value_str:
        return float(value_str.replace('B', '').replace(',', '')) * 1e9
    elif 'M' in value_str:
        return float(value_str.replace('M', '').replace(',', '')) * 1e6
    return float(value_str.replace(',', ''))

In [ ]:
data['Vol.'] = data['Vol.'].apply(convert_vol)
print(data.dtypes)
print(data.head())

Date        datetime64[ns]
Price              float64
Open               float64
High               float64
Low                float64
Vol.               float64
Change %           float64
dtype: object
        Date    Price     Open     High      Low          Vol.  Change %
0 2015-11-24  7831.60  7837.00  7870.35  7812.65  1.345600e+11     -0.22
1 2015-11-23  7849.25  7869.50  7877.50  7825.20  1.308700e+11     -0.09
2 2015-11-20  7856.55  7841.90  7906.95  7817.80  1.566100e+11      0.18
3 2015-11-19  7842.75  7788.50  7854.90  7765.45  1.367000e+11      1.43
4 2015-11-18  7731.80  7823.15  7843.40  7725.05  1.480400e+11     -1.35

Date        datetime64[ns]
Price              float64
Open               float64
High               float64
Low                float64
Vol.               float64
Change %           float64
dtype: object

## feature addition

### SMA

In [ ]:
# Calculate Simple Moving Average (SMA)
# 10-day SMA, adjust window as needed
data['SMA_10'] = data['Price'].rolling(window=10).mean()

In [ ]:
# Replace NaN values with 0
data['SMA_10'] = data['SMA_10'].fillna(0)

In [ ]:
# Calculate Relative Strength Index (RSI)
window_length = 14  # Typical window length for RSI

# Calculate price difference
delta = data['Price'].diff()

# Calculate gains (positive deltas) and losses (negative deltas)
gain = delta.where(delta > 0, 0)
loss = -delta.where(delta < 0, 0)

# Calculate the average gain and loss
avg_gain = gain.rolling(window=window_length, min_periods=1).mean()
avg_loss = loss.rolling(window=window_length, min_periods=1).mean()

# Calculate the RSI
rs = avg_gain / avg_loss
data['RSI'] = 100 - (100 / (1 + rs))

In [40]:
# Fill any NaN values that might have resulted from rolling calculations
data.fillna(0, inplace=True)

In [43]:
# Calculate Exponential Moving Average (EMA) with a span of 12 and 26
data['EMA_12'] = data['Price'].ewm(span=12, adjust=False).mean()
data['EMA_26'] = data['Price'].ewm(span=26, adjust=False).mean()

# Calculate MACD (difference between 12-day and 26-day EMA)
data['MACD'] = data['EMA_12'] - data['EMA_26']

# Calculate the Signal Line (9-day EMA of MACD)
data['Signal_Line'] = data['MACD'].ewm(span=9, adjust=False).mean()

In [47]:
data.head()

,Date,Price,Open,High,Low,Vol.,Change %,SMA_10,RSI,EMA_12,EMA_26,MACD,Signal_Line
0,2015-11-24,7831.60,7837.00,7870.35,7812.65,1.345600e+11,-0.22,0.0,0.000000,7831.600000,7831.600000,0.000000,0.000000
1,2015-11-23,7849.25,7869.50,7877.50,7825.20,1.308700e+11,-0.09,0.0,100.000000,7834.315385,7832.907407,1.407977,0.281595
2,2015-11-20,7856.55,7841.90,7906.95,7817.80,1.566100e+11,0.18,0.0,100.000000,7837.736095,7834.658711,3.077384,0.840753
3,2015-11-19,7842.75,7788.50,7854.90,7765.45,1.367000e+11,1.43,0.0,64.387097,7838.507465,7835.258065,3.249399,1.322482
4,2015-11-18,7731.80,7823.15,7843.40,7725.05,1.480400e+11,-1.35,0.0,16.666667,7822.090932,7827.594505,-5.503573,-0.042729

In [46]:
data[["EMA_12","EMA_26","MACD","Signal_Line"]].isnull().sum()

EMA_12         0
EMA_26         0
MACD           0
Signal_Line    0
dtype: int64

In [48]:
# Calculating Bollinger Bands
sma = data['Price'].rolling(window=20).mean()
std = data['Price'].rolling(window=20).std()

# Calculate the Upper and Lower Bollinger Bands
data['Upper Band'] = sma + (2 * std)
data['Lower Band'] = sma - (2 * std)

In [58]:
data[['Upper Band', 'Lower Band']] = data[['Upper Band', 'Lower Band']].fillna(0)

In [59]:
# NOTE: rows until index 18 have to be removed as they contain 0s in SMA_10, Upper Band, Lower Band

,Date,Price,Open,High,Low,Vol.,Change %,SMA_10,RSI,EMA_12,EMA_26,MACD,Signal_Line,Upper Band,Lower Band
0,2015-11-24,7831.60,7837.00,7870.35,7812.65,1.345600e+11,-0.22,0.000,0.000000,7831.600000,7831.600000,0.000000,0.000000,0.000000,0.000000
1,2015-11-23,7849.25,7869.50,7877.50,7825.20,1.308700e+11,-0.09,0.000,100.000000,7834.315385,7832.907407,1.407977,0.281595,0.000000,0.000000
2,2015-11-20,7856.55,7841.90,7906.95,7817.80,1.566100e+11,0.18,0.000,100.000000,7837.736095,7834.658711,3.077384,0.840753,0.000000,0.000000
3,2015-11-19,7842.75,7788.50,7854.90,7765.45,1.367000e+11,1.43,0.000,64.387097,7838.507465,7835.258065,3.249399,1.322482,0.000000,0.000000
4,2015-11-18,7731.80,7823.15,7843.40,7725.05,1.480400e+11,-1.35,0.000,16.666667,7822.090932,7827.594505,-5.503573,-0.042729,0.000000,0.000000
5,2015-11-17,7837.55,7848.75,7860.45,7793.00,1.494500e+11,0.40,0.000,51.164611,7824.469250,7828.331949,-3.862699,-0.806723,0.000000,0.000000
6,2015-11-16,7806.60,7732.95,7838.85,7714.15,1.541400e+11,0.57,0.000,45.635475,7821.720135,7826.722175,-5.002040,-1.645786,0.000000,0.000000
7,2015-11-13,7762.25,7762.45,7775.10,7730.90,1.658800e+11,-0.80,0.000,39.516251,7812.570883,7821.946458,-9.375575,-3.191744,0.000000,0.000000
8,2015-11-11,7825.00,7838.80,7847.95,7819.10,2.238000e+11,0.54,0.000,49.161372,7814.483055,7822.172647,-7.689592,-4.091314,0.000000,0.000000
9,2015-11-10,7783.35,7877.60,7885.10,7772.85,1.702700e+11,-1.67,7812.670,44.455935,7809.693354,7819.296895,-9.603541,-5.193759,0.000000,0.000000
10,2015-11-09,7915.20,7788.25,7937.75,7771.70,2.184200e+11,-0.49,7821.030,57.372134,7825.925146,7826.400829,-0.475683,-4.250144,0.000000,0.000000
11,2015-11-06,7954.30,7956.55,8002.65,7926.15,2.263300e+11,-0.01,7831.535,60.122092,7845.675123,7835.874841,9.800282,-1.440059,0.000000,0.000000
12,2015-11-05,7955.45,8030.35,8031.20,7944.10,1.362200e+11,-1.05,7841.425,60.197612,7862.563566,7844.732261,17.831305,2.414214,0.000000,0.000000
13,2015-11-04,8040.20,8104.90,8116.10,8027.30,1.259400e+11,-0.25,7861.170,65.072254,7889.892248,7859.211352,30.680896,8.067550,0.000000,0.000000
14,2015-11-03,8060.70,8086.35,8100.35,8031.75,1.366200e+11,0.12,7894.060,66.077193,7916.170364,7874.136437,42.033926,14.860826,0.000000,0.000000
15,2015-11-02,8050.80,8054.55,8060.70,7995.60,1.403200e+11,-0.19,7915.385,64.299397,7936.882616,7887.222627,49.659988,21.820658,0.000000,0.000000
16,2015-10-30,8065.80,8123.55,8146.10,8044.40,2.056600e+11,-0.57,7941.305,64.685241,7956.716059,7900.450581,56.265479,28.709622,0.000000,0.000000
17,2015-10-29,8111.75,8175.45,8179.60,8098.00,2.242300e+11,-0.73,7976.255,68.063390,7980.567435,7916.102390,64.465045,35.860707,0.000000,0.000000
18,2015-10-28,8171.20,8188.90,8209.10,8131.80,1.947100e+11,-0.75,8010.875,81.698168,8009.895522,7934.998509,74.897013,43.667968,0.000000,0.000000
19,2015-10-27,8232.90,8230.35,8241.95,8217.05,1.614900e+11,-0.33,8055.830,80.456051,8044.203903,7957.065286,87.138617,52.362098,8224.170272,7644.329728
20,2015-10-26,8260.55,8333.65,8336.30,8252.05,1.380100e+11,-0.42,8090.365,85.149051,8077.487918,7979.545635,97.942283,61.478135,8275.562650,7635.832350